Merge the 3 update dataset endpoints
DouglasConnect/edelweiss-data-python pull request #8
Opened 2020-04-04 19:52 UTC by istreeter

Closes #7

2020-04-25 09:39 UTC, istreeter commented
@matijapretnar @danyx23 This is a fairly old PR - I only just noticed it never got reviewed.

2020-04-25 22:14 UTC, matijapretnar requested changes

2020-04-25 22:14 UTC, matijapretnar commented on edelweiss_data/api.py
> +            # TODO: The need for json.dumps will get removed in a near-future version of edelweiss server.
I think this is resolved now

2020-04-25 22:14 UTC, matijapretnar commented on edelweiss_data/api.py
> +        :param data_source: A new data_source for the dataset. See set_data_source for a description of a data source.
`set_data_source` takes a dataset, not a dict as an argument, so perhaps this should be unified in some reasonable way?

2020-04-27 07:03 UTC, danyx23 approved these changes

2020-04-27 08:56 UTC, matijapretnar approved these changes

2020-04-27 09:11 UTC, merged